/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/app'
import { Route as IndexImport } from './routes/index'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AppTgSignInImport } from './routes/app/tg-sign-in'
import { Route as AppOnboardingImport } from './routes/app/onboarding'
import { Route as AppTabBarImport } from './routes/app/_tab-bar'
import { Route as AppTabBarGraphImport } from './routes/app/_tab-bar/graph'
import { Route as AppTabBarContactsImport } from './routes/app/_tab-bar/contacts'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AppTgSignInRoute = AppTgSignInImport.update({
  id: '/tg-sign-in',
  path: '/tg-sign-in',
  getParentRoute: () => AppRoute,
} as any)

const AppOnboardingRoute = AppOnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)

const AppTabBarRoute = AppTabBarImport.update({
  id: '/_tab-bar',
  getParentRoute: () => AppRoute,
} as any)

const AppTabBarGraphRoute = AppTabBarGraphImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppTabBarRoute,
} as any)

const AppTabBarContactsRoute = AppTabBarContactsImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppTabBarRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/app/_tab-bar': {
      id: '/app/_tab-bar'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppTabBarImport
      parentRoute: typeof AppImport
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingImport
      parentRoute: typeof AppImport
    }
    '/app/tg-sign-in': {
      id: '/app/tg-sign-in'
      path: '/tg-sign-in'
      fullPath: '/app/tg-sign-in'
      preLoaderRoute: typeof AppTgSignInImport
      parentRoute: typeof AppImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
    '/app/_tab-bar/contacts': {
      id: '/app/_tab-bar/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppTabBarContactsImport
      parentRoute: typeof AppTabBarImport
    }
    '/app/_tab-bar/graph': {
      id: '/app/_tab-bar/graph'
      path: '/graph'
      fullPath: '/app/graph'
      preLoaderRoute: typeof AppTabBarGraphImport
      parentRoute: typeof AppTabBarImport
    }
  }
}

// Create and export the route tree

interface AppTabBarRouteChildren {
  AppTabBarContactsRoute: typeof AppTabBarContactsRoute
  AppTabBarGraphRoute: typeof AppTabBarGraphRoute
}

const AppTabBarRouteChildren: AppTabBarRouteChildren = {
  AppTabBarContactsRoute: AppTabBarContactsRoute,
  AppTabBarGraphRoute: AppTabBarGraphRoute,
}

const AppTabBarRouteWithChildren = AppTabBarRoute._addFileChildren(
  AppTabBarRouteChildren,
)

interface AppRouteChildren {
  AppTabBarRoute: typeof AppTabBarRouteWithChildren
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppTgSignInRoute: typeof AppTgSignInRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppTabBarRoute: AppTabBarRouteWithChildren,
  AppOnboardingRoute: AppOnboardingRoute,
  AppTgSignInRoute: AppTgSignInRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppTabBarRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/tg-sign-in': typeof AppTgSignInRoute
  '/app/': typeof AppIndexRoute
  '/app/contacts': typeof AppTabBarContactsRoute
  '/app/graph': typeof AppTabBarGraphRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/tg-sign-in': typeof AppTgSignInRoute
  '/app/contacts': typeof AppTabBarContactsRoute
  '/app/graph': typeof AppTabBarGraphRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/_tab-bar': typeof AppTabBarRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/tg-sign-in': typeof AppTgSignInRoute
  '/app/': typeof AppIndexRoute
  '/app/_tab-bar/contacts': typeof AppTabBarContactsRoute
  '/app/_tab-bar/graph': typeof AppTabBarGraphRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/onboarding'
    | '/app/tg-sign-in'
    | '/app/'
    | '/app/contacts'
    | '/app/graph'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/onboarding'
    | '/app/tg-sign-in'
    | '/app/contacts'
    | '/app/graph'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/_tab-bar'
    | '/app/onboarding'
    | '/app/tg-sign-in'
    | '/app/'
    | '/app/_tab-bar/contacts'
    | '/app/_tab-bar/graph'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app": {
      "filePath": "app.tsx",
      "children": [
        "/app/_tab-bar",
        "/app/onboarding",
        "/app/tg-sign-in",
        "/app/"
      ]
    },
    "/app/_tab-bar": {
      "filePath": "app/_tab-bar.tsx",
      "parent": "/app",
      "children": [
        "/app/_tab-bar/contacts",
        "/app/_tab-bar/graph"
      ]
    },
    "/app/onboarding": {
      "filePath": "app/onboarding.tsx",
      "parent": "/app"
    },
    "/app/tg-sign-in": {
      "filePath": "app/tg-sign-in.tsx",
      "parent": "/app"
    },
    "/app/": {
      "filePath": "app/index.tsx",
      "parent": "/app"
    },
    "/app/_tab-bar/contacts": {
      "filePath": "app/_tab-bar/contacts.tsx",
      "parent": "/app/_tab-bar"
    },
    "/app/_tab-bar/graph": {
      "filePath": "app/_tab-bar/graph.tsx",
      "parent": "/app/_tab-bar"
    }
  }
}
ROUTE_MANIFEST_END */
